version: '3.8'

services:
  # SQL Database service (SQL Server)
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqldb
    healthcheck:
      test: ["/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "sjjHHS239:_s23", "-Q", "SELECT 1", "-b", "-o", "/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sjjHHS239:_s23
    ports:
      - "1433:1433"  # Expose SQL server port
    networks:
      - backend-network
    volumes:
      - sql-data:/var/opt/mssql

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - backend-network
    volumes:
      - mongo-data:/data/db

  # .NET API service
  dotnet-api:
    build:
      context: .  # Path to your project directory
      dockerfile: Dockerfile  # Path to your Dockerfile
    container_name: dotnet-api
    ports:
      - "5050:8080"  # Map port 5050 to 8080 inside the container
    networks:
      - backend-network
    depends_on:
      sqldb:
        condition: service_healthy
      mongodb:
       condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DatabaseName=Assignment3
      - DefaultConnection=Data Source=sqldb;Initial Catalog={DatabaseName};User ID=sa;Password=sjjHHS239:_s23;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False;
      - MongoDBSettings__ConnectionString=mongodb://mongodb:27017/assign3
      - MongoDBSettings__DatabaseName=assign3

networks:
  backend-network:
    driver: bridge

volumes:
  sql-data:
  mongo-data:
