version: '3.8'

services:
  # SQL Database service (SQL Server)
  sql3:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql3
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AU650889?
    ports:
      - "1433:1433"  # Expose SQL server port
    networks:
      - backend-network
    volumes:
      - sql-data6:/var/opt/mssql

  # MongoDB service
  mongoex3:
    image: mongo:latest
    container_name: mongoex3
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - backend-network
    volumes:
      - mongo-data:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d

  # .NET API service
  dotnet-api:
    build:
      context: .  # Path to your project directory
      dockerfile: Dockerfile  # Path to your Dockerfile
    container_name: dotnet-api
    ports:
      - "8080:8080"  # Align with applicationUrl in launchsettings
    networks:
      - backend-network
    depends_on:
      - sql3
      - mongoex3
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - DatabaseName=Assignment3
      - DefaultConnection=Server=sql3;Initial Catalog={DatabaseName};User ID=sa;Password=AU650889?;TrustServerCertificate=True
      - MongoDBSettings__ConnectionString=mongodb://mongoex3:27017/assign3
      - MongoDBSettings__DatabaseName=assign3

networks:
  backend-network:
    driver: bridge

volumes:
  sql-data6:
  mongo-data: